# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Trackable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Trackable.proto',
  package='RTLSProtocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fTrackable.proto\x12\x0cRTLSProtocol\"\x87\x06\n\tTrackable\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63uid\x18\x02 \x01(\x0c\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x66rame_ID\x18\n \x01(\x04\x12\x11\n\ttimestamp\x18\x0b \x01(\x04\x12\x0f\n\x07\x63ontext\x18\x0c \x01(\x0c\x12\x32\n\x08position\x18\x04 \x01(\x0b\x32 .RTLSProtocol.Trackable.Position\x12\x38\n\x0borientation\x18\x05 \x01(\x0b\x32#.RTLSProtocol.Trackable.Orientation\x12\x32\n\x08velocity\x18\x06 \x01(\x0b\x32 .RTLSProtocol.Trackable.Velocity\x12:\n\x0c\x61\x63\x63\x65leration\x18\x07 \x01(\x0b\x32$.RTLSProtocol.Trackable.Acceleration\x12\x41\n\x10\x61ngular_velocity\x18\x08 \x01(\x0b\x32\'.RTLSProtocol.Trackable.AngularVelocity\x12I\n\x14\x61ngular_acceleration\x18\t \x01(\x0b\x32+.RTLSProtocol.Trackable.AngularAcceleration\x1a+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x39\n\x0bOrientation\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x1a+\n\x08Velocity\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a/\n\x0c\x41\x63\x63\x65leration\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x32\n\x0f\x41ngularVelocity\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x36\n\x13\x41ngularAcceleration\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"b\n\x0eTrackableFrame\x12\x10\n\x08\x66rame_ID\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12+\n\ntrackables\x18\x03 \x03(\x0b\x32\x17.RTLSProtocol.Trackableb\x06proto3')
)




_TRACKABLE_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='RTLSProtocol.Trackable.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.Position.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.Position.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.Position.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=548,
)

_TRACKABLE_ORIENTATION = _descriptor.Descriptor(
  name='Orientation',
  full_name='RTLSProtocol.Trackable.Orientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.Orientation.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.Orientation.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.Orientation.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='RTLSProtocol.Trackable.Orientation.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=607,
)

_TRACKABLE_VELOCITY = _descriptor.Descriptor(
  name='Velocity',
  full_name='RTLSProtocol.Trackable.Velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.Velocity.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.Velocity.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.Velocity.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=652,
)

_TRACKABLE_ACCELERATION = _descriptor.Descriptor(
  name='Acceleration',
  full_name='RTLSProtocol.Trackable.Acceleration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.Acceleration.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.Acceleration.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.Acceleration.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=701,
)

_TRACKABLE_ANGULARVELOCITY = _descriptor.Descriptor(
  name='AngularVelocity',
  full_name='RTLSProtocol.Trackable.AngularVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.AngularVelocity.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.AngularVelocity.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.AngularVelocity.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=753,
)

_TRACKABLE_ANGULARACCELERATION = _descriptor.Descriptor(
  name='AngularAcceleration',
  full_name='RTLSProtocol.Trackable.AngularAcceleration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RTLSProtocol.Trackable.AngularAcceleration.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RTLSProtocol.Trackable.AngularAcceleration.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='RTLSProtocol.Trackable.AngularAcceleration.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=809,
)

_TRACKABLE = _descriptor.Descriptor(
  name='Trackable',
  full_name='RTLSProtocol.Trackable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RTLSProtocol.Trackable.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cuid', full_name='RTLSProtocol.Trackable.cuid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='RTLSProtocol.Trackable.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_ID', full_name='RTLSProtocol.Trackable.frame_ID', index=3,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RTLSProtocol.Trackable.timestamp', index=4,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='RTLSProtocol.Trackable.context', index=5,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='RTLSProtocol.Trackable.position', index=6,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='RTLSProtocol.Trackable.orientation', index=7,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='RTLSProtocol.Trackable.velocity', index=8,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='RTLSProtocol.Trackable.acceleration', index=9,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='RTLSProtocol.Trackable.angular_velocity', index=10,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_acceleration', full_name='RTLSProtocol.Trackable.angular_acceleration', index=11,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRACKABLE_POSITION, _TRACKABLE_ORIENTATION, _TRACKABLE_VELOCITY, _TRACKABLE_ACCELERATION, _TRACKABLE_ANGULARVELOCITY, _TRACKABLE_ANGULARACCELERATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=809,
)


_TRACKABLEFRAME = _descriptor.Descriptor(
  name='TrackableFrame',
  full_name='RTLSProtocol.TrackableFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_ID', full_name='RTLSProtocol.TrackableFrame.frame_ID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RTLSProtocol.TrackableFrame.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackables', full_name='RTLSProtocol.TrackableFrame.trackables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=909,
)

_TRACKABLE_POSITION.containing_type = _TRACKABLE
_TRACKABLE_ORIENTATION.containing_type = _TRACKABLE
_TRACKABLE_VELOCITY.containing_type = _TRACKABLE
_TRACKABLE_ACCELERATION.containing_type = _TRACKABLE
_TRACKABLE_ANGULARVELOCITY.containing_type = _TRACKABLE
_TRACKABLE_ANGULARACCELERATION.containing_type = _TRACKABLE
_TRACKABLE.fields_by_name['position'].message_type = _TRACKABLE_POSITION
_TRACKABLE.fields_by_name['orientation'].message_type = _TRACKABLE_ORIENTATION
_TRACKABLE.fields_by_name['velocity'].message_type = _TRACKABLE_VELOCITY
_TRACKABLE.fields_by_name['acceleration'].message_type = _TRACKABLE_ACCELERATION
_TRACKABLE.fields_by_name['angular_velocity'].message_type = _TRACKABLE_ANGULARVELOCITY
_TRACKABLE.fields_by_name['angular_acceleration'].message_type = _TRACKABLE_ANGULARACCELERATION
_TRACKABLEFRAME.fields_by_name['trackables'].message_type = _TRACKABLE
DESCRIPTOR.message_types_by_name['Trackable'] = _TRACKABLE
DESCRIPTOR.message_types_by_name['TrackableFrame'] = _TRACKABLEFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trackable = _reflection.GeneratedProtocolMessageType('Trackable', (_message.Message,), {

  'Position' : _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_POSITION,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.Position)
    })
  ,

  'Orientation' : _reflection.GeneratedProtocolMessageType('Orientation', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_ORIENTATION,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.Orientation)
    })
  ,

  'Velocity' : _reflection.GeneratedProtocolMessageType('Velocity', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_VELOCITY,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.Velocity)
    })
  ,

  'Acceleration' : _reflection.GeneratedProtocolMessageType('Acceleration', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_ACCELERATION,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.Acceleration)
    })
  ,

  'AngularVelocity' : _reflection.GeneratedProtocolMessageType('AngularVelocity', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_ANGULARVELOCITY,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.AngularVelocity)
    })
  ,

  'AngularAcceleration' : _reflection.GeneratedProtocolMessageType('AngularAcceleration', (_message.Message,), {
    'DESCRIPTOR' : _TRACKABLE_ANGULARACCELERATION,
    '__module__' : 'Trackable_pb2'
    # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable.AngularAcceleration)
    })
  ,
  'DESCRIPTOR' : _TRACKABLE,
  '__module__' : 'Trackable_pb2'
  # @@protoc_insertion_point(class_scope:RTLSProtocol.Trackable)
  })
_sym_db.RegisterMessage(Trackable)
_sym_db.RegisterMessage(Trackable.Position)
_sym_db.RegisterMessage(Trackable.Orientation)
_sym_db.RegisterMessage(Trackable.Velocity)
_sym_db.RegisterMessage(Trackable.Acceleration)
_sym_db.RegisterMessage(Trackable.AngularVelocity)
_sym_db.RegisterMessage(Trackable.AngularAcceleration)

TrackableFrame = _reflection.GeneratedProtocolMessageType('TrackableFrame', (_message.Message,), {
  'DESCRIPTOR' : _TRACKABLEFRAME,
  '__module__' : 'Trackable_pb2'
  # @@protoc_insertion_point(class_scope:RTLSProtocol.TrackableFrame)
  })
_sym_db.RegisterMessage(TrackableFrame)


# @@protoc_insertion_point(module_scope)
